# Generated by Django 4.0.6 on 2022-08-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_time',
        ),
    ]
